before_commands:
    - "composer install"

imports:
    - php

filter:
    excluded-paths: [ spec/*, vendor/* ]

tools:
    custom_commands:
        -
            scope: file
            command: vendor/phpspec/phpspec/bin/phpspec run %pathname% -f scrutinizer --no-code-generation || true